### ISSUE TITLE
I can not operate, please ask your detailed operation steps

### ISSUE THREAD

**Issue by Hao-1209** [starburst997/Unity.Trimmer#1]
I downloaded the project and AssetsTools.NET, but I found that I did not know how to proceed to the next step

**Comment by starburst997** [comment]
I'll add more detailed instructions when I have time, but the gist of it is that you can generate a new `unity_default_resources` file with this project that is smaller than the one provided by Unity.

There is already an output available in the [Extra folder](https://github.com/starburst997/Unity.Trimmer/blob/21d8cb4b4c43520f961df06212a537f58bd2f5b4/Extra/unity_default_resources) that is compatible with Unity 2021.1.28f1, you can then replace the one from Unity (`C:\Program Files\Unity\Hub\Editor\XXXXXXX\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\data\unity_default_resources`) and enjoy smaller webgl builds.

Please be aware that this particular file is not compatible with every Unity version so if it isn't compatible with the one you are using you need to build it using this program. That part I will add further instructions when I have time and since their seems to be interests maybe even keep releases of the output file for each major unity version so manually building it wouldn't be necessary.

**Comment by Hao-1209** [comment]
That sounds awesome

I replaced the unity_default_resources file in the Extra folder of this project to my installation path, but an error was reported after the package was sent out, indicating that the version did not match

The version I used was unity2021.2.18f1

**Comment by Hao-1209** [comment]
I really look forward to your writing the detailed instructions , and I will learn it
